default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 719171
  host: localhost

development:
  <<: *default
  database: hello_rails

test:
  <<: *default
  database: gemstone_blog_test

production:
  <<: *default
  database: gemstone_blog_prod